---
- hosts: postgres
  sudo: yes
  vars:
    db_user: uad
    db_password: abc
    database: uad
  roles:
    - postgresql

- hosts: activemq
  sudo: yes
  vars:
    - app_user: uad
  roles:
    - java
    - activemq

- hosts: redis
  sudo: yes
  roles:
    - redis

- hosts: webserver
  sudo: yes
  vars:
    app_user: uad
    db_user: uad
    db_password: abc
    # Use the first host in 'postgres' group as the DB server
    db_server: "{{ hostvars[groups['postgres'][0]].ansible_eth0.ipv4.address }}"
  roles:
    - user
    - java
    - ant
    - resin
    - uad
